import 'package:hive_flutter/hive_flutter.dart';
import '../models/mood_entry.dart';
import '../models/profile.dart';

class HiveInit {
  static const String moodBoxName = 'mood_box';
  static const String profileBoxName = 'profile_box';

  static Future<void> init() async {
    await Hive.initFlutter();
    
    // Register adapters (generated by build_runner)
    if (!Hive.isAdapterRegistered(0)) {
      Hive.registerAdapter(MoodEntryAdapter());
    }
    if (!Hive.isAdapterRegistered(1)) {
      Hive.registerAdapter(ProfileAdapter());
    }
    
    // Open boxes
    await Hive.openBox<MoodEntry>(moodBoxName);
    await Hive.openBox<Profile>(profileBoxName);
  }

  static Box<MoodEntry> get moodBox => Hive.box<MoodEntry>(moodBoxName);
  static Box<Profile> get profileBox => Hive.box<Profile>(profileBoxName);
}

